//go:build linux

package nftfw

// The boot-time firewall config. gopit owns /etc/nftables.conf: the agent
// rewrites it atomically on every change and the distro nftables service
// loads it at boot. The format is generated strictly by renderConf and parsed
// back by loadConf (used to recover the managed state at agent startup when
// the kernel table is missing).

import (
	"fmt"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// confMarker marks the file as gopit-managed. confForeign treats any existing
// file without it as foreign and never overwrites it.
const confMarker = "# Generated by gopitd"

// renderConf renders the nftables boot config for the given logical state.
var ruleLineRe = regexp.MustCompile(`^\t\t(?:iifname "([^"]+)" )?(?:(ip|ip6) saddr (\S+) )?(tcp|udp) dport (\d+) (accept|drop|reject(?: with tcp reset)?)$`)
var policyRe = regexp.MustCompile(`policy (accept|drop);`)
var jumpRe = regexp.MustCompile(`jump gopit-input`)

func renderConf(enabled bool, rules []lrule) string {
	var b strings.Builder
	b.WriteString("#!/usr/sbin/nft -f\n")
	b.WriteString(confMarker + " — do not edit; rewritten by the agent on every change.\n")
	b.WriteString("\ntable inet gopit\nflush table inet gopit\n\ntable inet gopit {\n")
	pol := "accept"
	if enabled {
		pol = "drop"
	}
	b.WriteString("\tchain input {\n")
	b.WriteString(fmt.Sprintf("\t\ttype filter hook input priority filter; policy %s;\n", pol))
	if enabled {
		b.WriteString("\t\tjump gopit-input\n")
	}
	b.WriteString("\t}\n\tchain gopit-input {\n")
	b.WriteString("\t\tct state established,related accept\n")
	b.WriteString("\t\tiifname \"lo\" accept\n")
	for _, r := range rules {
		for _, proto := range ruleProtos(r.proto) {
			rr := r
			rr.proto = proto
			b.WriteString("\t\t" + renderRule(rr) + "\n")
		}
	}
	b.WriteString("\t}\n}\n")
	return b.String()
}

func ruleProtos(proto string) []string {
	if proto == "both" {
		return []string{"tcp", "udp"}
	}
	return []string{proto}
}

func renderRule(r lrule) string {
	var b strings.Builder
	if r.iface != "" {
		fmt.Fprintf(&b, "iifname %q ", r.iface)
	}
	if r.from != "" {
		ip := net.ParseIP(r.from)
		fam := "ip"
		if ip != nil && ip.To4() == nil {
			fam = "ip6"
		}
		fmt.Fprintf(&b, "%s saddr %s ", fam, r.from)
	}
	fmt.Fprintf(&b, "%s dport %d ", r.proto, r.port)
	switch r.action {
	case "deny":
		b.WriteString("drop")
	case "reject":
		if r.proto == "tcp" {
			b.WriteString("reject with tcp reset")
		} else {
			b.WriteString("reject")
		}
	default:
		b.WriteString("accept")
	}
	return b.String()
}

// loadConf reads the persisted boot config back into logical state. A missing
// file means a fresh install (inactive, no rules); a foreign file (no gopit
// marker) is treated the same.
func loadConf(path string) (enabled bool, rules []lrule, err error) {
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil, nil
		}
		return false, nil, err
	}
	text := string(b)
	if !strings.Contains(text, confMarker) {
		return false, nil, nil
	}
	m := policyRe.FindStringSubmatch(text)
	enabled = len(m) == 2 && m[1] == "drop" && jumpRe.MatchString(text)
	for _, line := range strings.Split(text, "\n") {
		m := ruleLineRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		proto, port, verb := m[4], atoi(m[5]), m[6]
		action := "allow"
		switch {
		case verb == "drop":
			action = "deny"
		case strings.HasPrefix(verb, "reject"):
			action = "reject"
		}
		rules = append(rules, lrule{proto: proto, port: port, action: action, from: strings.TrimSpace(m[3]), iface: m[1]})
	}
	return enabled, mergeClumped(rules), nil
}

// mergeClumped merges adjacent tcp+udp twins rendered from one "both" rule
// (same port/from/iface/action) back into a single logical rule.
func mergeClumped(rules []lrule) []lrule {
	var out []lrule
	for i := 0; i < len(rules); i++ {
		r := rules[i]
		if r.proto == "tcp" && i+1 < len(rules) && rules[i+1].proto == "udp" && lruleKey(r) == lruleKey(rules[i+1]) {
			r.proto = "both"
			i++
		}
		out = append(out, r)
	}
	return out
}

func lruleKey(r lrule) string {
	return fmt.Sprintf("%s|%d|%s|%s", r.iface, r.port, r.action, r.from)
}

// confForeign reports whether path exists with real content that is not
// gopit-managed (no marker). Such a file is never overwritten: it will be
// reloaded at boot by the nftables service without the gopit table.
func confForeign(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	if strings.Contains(string(b), confMarker) {
		return false
	}
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") && !strings.HasPrefix(line, "!") {
			return true
		}
	}
	return false
}

// writeConf atomically replaces the boot config (fsync'd so a power loss
// can't leave a partial file: that would silently disable the firewall at boot).
func writeConf(path string, enabled bool, rules []lrule) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(renderConf(enabled, rules)), 0o644); err != nil {
		return err
	}
	f, err := os.Open(tmp)
	if err != nil {
		return err
	}
	if err := f.Sync(); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		return err
	}
	if d, err := os.Open(filepath.Dir(path)); err == nil {
		d.Sync()
		d.Close()
	}
	return nil
}

// errLogf logs a nftfw warning; a non-nil err is appended.
func errLogf(err error, format string, args ...any) {
	if err != nil {
		slog.Warn(fmt.Sprintf("nftfw: %s: %v", format, err), args...)
	} else {
		slog.Warn("nftfw: "+format, args...)
	}
}

func atoi(s string) int {
	if len(s) > 5 { // >65535 cannot be a port
		return 0
	}
	n := 0
	for _, c := range s {
		if c < '0' || c > '9' {
			return n
		}
		n = n*10 + int(c-'0')
		if n > 65535 {
			return 0
		}
	}
	return n
}
